### ISSUE TITLE
思维导图没有正确显示

### ISSUE THREAD

**Issue by nondevops** [HunterXuan/hexo-simple-mindmap#1]
环境:
hexo3.9
next7

部署:
npm install hexo-simple-mindmap --save

现象:
插件安装成功,使用时未能展示思维导图的样式,控制台发现有报错
![image](https://user-images.githubusercontent.com/12181410/68083681-84d23a00-fe66-11e9-8719-0ba535cb09a3.png)

![image](https://user-images.githubusercontent.com/12181410/68083593-4e47ef80-fe65-11e9-872d-5d6a15c76e64.png)
``` nodejs
$(document).ready(function(){$(".mindmap").each(function(){MM_FUNCS.drawMindMap(this)})});var MM_FUNCS={li2jsonData:function(c){var a;var b=c.children("a:first");if(b.length!==0){a={"data":{"text":b.text(),"hyperlink":b.attr("href")}}}else{a={"data":{"text":c[0].childNodes[0].nodeValue.trim()}}}c.find("> ul > li").each(function(){if(!a.hasOwnProperty("children")){a.children=[]}a.children.push(MM_FUNCS.li2jsonData($(this)))});return a},drawMindMap:function(a){var d=$(a).find(">ul:first");var c={"root":{}};var b=new kityminder.Minder({renderTo:a});c.root=MM_FUNCS.li2jsonData(d.children("li:first"));b.importData("json",JSON.stringify(c));b.disable();b.execCommand("hand");$(d).hide()}};

```

![image](https://user-images.githubusercontent.com/12181410/68083698-cb279900-fe66-11e9-976a-bb8fb05b3817.png)
![image](https://user-images.githubusercontent.com/12181410/68083720-0aee8080-fe67-11e9-8f0a-92674f3f225b.png)

**Comment by HunterXuan** [comment]
需要先引入 jquery
