### ISSUE TITLE
bug: root节点未正常转义为a标签

### ISSUE THREAD

**Issue by iefhong** [HunterXuan/hexo-simple-mindmap#2]
![hexosimplemindmaproot2urlexception.png](https://coding-hexo-bucket.oss-cn-shenzhen.aliyuncs.com/hexo-client/2020/03/29/0ea1cf70-7171-11ea-819d-414c92358111.png)

hexo 4.2.0 , 
root节点为链接时未正常转义为a标签
导致思维导图生成失败
c[0].childNodes[0].nodeValue.trim() // 未检索到节点，报错

jquery.min.js:2 Uncaught TypeError: Cannot read property 'trim' of null

项目依赖
  "dependencies": {
    "hexo": "^4.0.0",
    "hexo-abbrlink": "^2.0.5",
    "hexo-blog-encrypt": "^3.0.12",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-index": "^1.0.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-marked": "^2.0.0",
    "hexo-renderer-stylus": "^1.1.0",
    "hexo-server": "^1.0.0",
    "hexo-symbols-count-time": "^0.7.0",
    "hexo-tag-cloud": "^2.1.1"
  }

主题 
next 7.7.1

目前不清楚是hexo版本问题还是其他插件导致的，囧

请问作者有没有什么解决思路？

**Comment by iefhong** [comment]
补充说明： 所有链接节点均存在该问题，未转义为a标签而是span标签

**Comment by HunterXuan** [comment]
我这边博客里有用到 a 标签：https://hunterx.xyz/hexo-simple-mindmap-plugin-intro.html

有点像是你的插件冲突？

不过你的 dependencies 咋没有 hexo-simple-mindmap，有点奇怪啊

**Comment by iefhong** [comment]
我用next的vendors.swig直接导入了依赖的js文件

**Comment by iefhong** [comment]
> 我用next的vendors.swig直接导入了依赖的js文件

{%- set js_vendors = js_vendors | attr('jquery', '//cdn.jsdelivr.net/npm/jquery@3/dist/jquery.min.js') %}
{%- set js_vendors = js_vendors | attr('kity', '//cdn.jsdelivr.net/npm/kity@2.0.4/dist/kity.min.js') %}
{%- set js_vendors = js_vendors | attr('kityminder', '//cdn.jsdelivr.net/npm/kityminder-core@1.4.50/dist/kityminder.core.min.js') %}
{%- set js_vendors = js_vendors | attr('mindmap', '//localhost:4000/lib/mindmap.min.js') %}

**Comment by HunterXuan** [comment]
我也是 NEXT 的主题，要不你试下 README 里说的安装方法吧

你这样引入，可能会有加载顺序的问题

**Comment by iefhong** [comment]
> 我也是 NEXT 的主题，要不你试下 README 里说的安装方法吧
> 
> 你这样引入，可能会有加载顺序的问题

方便提供一下hexo和next的版本么

**Comment by HunterXuan** [comment]
Hexo 3.9
Next 7.7.1

**Comment by iefhong** [comment]
感谢作者的回复，目前的解决方案
安装插件，npm install --save hexo-simple-mindmap
提示$ is not defined (jquery插件加载，但next移除了jquery)
修改 themes/next/layout/_scripts/vendors.swig
增加
{%- set js_vendors = js_vendors | attr('jquery', '//cdn.jsdelivr.net/npm/jquery@3/dist/jquery.min.js') %}

插件效果正常。

a标签没有正确转义应该是因为没有装作者的插件导致的

感谢作者的插件～

**Comment by iefhong** [comment]
插件冲突 hexo-blog-encrypt
该插件解密后仍会将a标签转义为span,故导致寻找节点失败报错。
两个插件不要在同一个页面使用...

**Comment by iefhong** [comment]
themes/next/_config.yml
关闭该属性，避免将a标签转义为span标签导致插件失效。

# Automatically add external URL with Base64 encrypt & decrypt.
exturl: false
