### ISSUE TITLE
中文乱码问题

### ISSUE THREAD

**Issue by small-rose** [HunterXuan/hexo-simple-mindmap#5]
作者，您好。
我在适应时遇到了中文乱码问题，请问需要额外设置什么吗？

![_C7W{GXE1{A}073H7$KBGSG](https://user-images.githubusercontent.com/29157746/87913720-2277a300-caa2-11ea-8646-094e3be499e8.png)

**Comment by HunterXuan** [comment]
一般来说，不需要额外设置什么，建议贴下具体链接，才好判断

**Comment by small-rose** [comment]
感谢作者解答，是我自己的文件编码问题，不是插件问题。抱歉，回复得有点迟。
