### ISSUE TITLE
Mindmap Rendering failed

### ISSUE THREAD

**Issue by willasas** [HunterXuan/hexo-simple-mindmap#6]
INFO  Validating config
- hexo: 5.1.0
- hexo-cli: 4.1.0
- os: Windows_NT 10.0.19041 win32 x64
- node: 12.18.0

DEMO
{% pullquote mindmap mindmap-md %}

- [hexo 思维导图使用](https://github.com/HunterXuan/hexo-simple-mindmap)
  - 前言
  - 操作指南
    - 准备需要的文件
    - 为主题添加 CSS/JS 文件
  - 使用方法

{% endpullquote %}

RESULT
[![daY1l6.png](https://s1.ax1x.com/2020/08/22/daY1l6.png)](https://imgchr.com/i/daY1l6)

**Comment by Clcanny** [comment]
Uncaught ReferenceError: $ is not defined
    at mindmap.min.js:1

**Comment by ZakYu** [comment]
> F12看下，应该有报错

你好，我这边也出现了这个问题。

报错：Uncaught ReferenceError: $ is not defined
    at mindmap.min.js:1

hexo: 5.3.0
hexo-cli: 4.2.0
os: Windows_NT 10.0.19042 win32 x64
node: 14.15.3
然后用的主题是NexT version 8.1.0

**Comment by ZakYu** [comment]
> > F12看下，应该有报错
> 
> 你好，我这边也出现了这个问题。
> 
> 报错：Uncaught ReferenceError: $ is not defined
> at mindmap.min.js:1
> 
> hexo: 5.3.0
> hexo-cli: 4.2.0
> os: Windows_NT 10.0.19042 win32 x64
> node: 14.15.3
> 然后用的主题是NexT version 8.1.0

在前面引入jQuery解决问题
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>

**Comment by HunterXuan** [comment]
已移除JQ库依赖，安装最新版本应该可破
